sudo: required
services:
   - docker

before_install:
   - docker build -t jayasaikrishna/react-frontend -f Dockerfile.dev .

scripts:
   - docker run -e CI=true jayasaikrishna/react-frontend npm run test -- --coverage
